#####################
# Site metadata
title: Tokenz (Obsidian plugin)
description: Smileys, emoticons or any type of short codes you create
email: fmoricz@gmail.com
author: ferenk
copyright: "Ferenc Moricz, 2024"
url: https://github.com/ferenk/github-tests
# baseurl: https://github.com/ferenk/github-tests
keywords: "github, test, token, shortcode, smiley, emoticon"
google_analytics: GTM-T47R9MX8
google_site_verification: dSXyPF8wjboE3nlpS89FWsrFjURklLwimxdmIloilrk
#####################
# Jekyll theme config
remote_theme: jeffreytse/jekyll-theme-yat
show_downloads: true
favicon: docs/img/tokenz_for_obsidian.ico
banner:
  image: "docs/img/tokenz_poster.jpg"
header_transparent: false
night_mode: "auto"
yat:
  date_format: "%Y-%m-%d %H:%M"
lang: "en"
sitemap: true
theme_color: greenblue
brand_color: orangered
selection:
  color: "#ff00ff"
  background_color: "yellow"
code_badge:
  enabled: false
defaults:
  home:
    heading: "Tokenz (for Obsidian)"
    subheading: "Smileys, emoticons - or YOUR own short code maps!"
