title: GitHub tests
description: Just to try features
remote_theme: jeffreytse/jekyll-theme-yat
#skin: air
url: "https://github.com/ferenk/github-tests"
keywords: "github, jekyll, test"
favicon: "/docs/img/tokenz.ico"
#################
# Header layout #
#################
background-img: "../docs/img/tokenz_poster.jpg"
