title: GitHub tests
description: Just to try features
<<<<<<< HEAD
remote_theme: kitian616/jekyll-TeXt-theme
=======
remote_theme: personal-jekyll-theme
>>>>>>> 33a43361822f555d0713e93f911603b3022edae2
url: "https://github.com/ferenk/github-tests"
keywords: "github, jekyll, test"
favicon: "/docs/img/tokenz.ico"
#################
# Header layout #
#################
background-img: "../docs/img/tokenz_poster.jpg"
