name: Test Actions

on:
  push:
    branches: [ master, ui_refresh ]

jobs:
  create_file:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world" > ./hello.txt
      - run: curl -s https://api.github.com/repos/ferenk/obsidian-tokenz/releases | egrep '"name"|"download_count"' > ./download_stats.txt
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./download_stats.txt
          tag: Web
          overwrite: true
          file_glob: true
